version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=arenapro
      - MYSQL_USER=root
      - MYSQL_PASSWORD=ADS2O23
    ports:
      - "3306:3306"
    networks:
      - arenanet

  arenapro:
    build:
      context: ./arenapro
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/arenapro
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=apppass
    networks:
      - arenanet

  login-service:
    build:
      context: ./login-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # se ele também usa DB, aponte para o mesmo:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/arenapro
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=apppass
    networks:
      - arenanet

networks:
  arenanet:
    driver: bridge
