version: "3.8"

services:
  login-service:
    build:
      context: ./login-service     # <--- Dockerfile dentro de login-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  arenapro:
    build:
      context: ./arenapro         # <--- Dockerfile dentro de arenapro
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
