version: '3.8'

services:
    login-service:
      build:
        context: ./login-service
      volumes:
        - ~/.m2:/root/.m2
      ports:
        - "8081:8080"

    arenapro:
      build:
        context: ./arenapro
      volumes:
        - ~/.m2:/root/.m2
      ports:
        - "8082:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=prod