version: '3.8'

services:
  login-service:
    build:
      context: ./login-service
    container_name: login-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  arenapro:
    build:
      context: ./arenapro
    container_name: arenapro
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod